### ISSUE TITLE
[BUG] Handover Plugin creates invalid properties

### ISSUE THREAD

**Issue by WelliSolutions** [eclipse-aaspe/package-explorer#193]
**Describe the bug**
The handover plugin creates invalid properties named `Document{0:00}`, `DigitalFile{0:00}` and `Language{0}`.

**To Reproduce**
1. Create a new AASX file or load an existing one.
2. Set the workspace to edit mode
3. Select an AAS
4. Make sure it does not have a documentation submodel already.
5. Select Workspace/Create/New submodel from plugin
6. Choose AasxpluginDocumentShelf|Document (recommended version)
7. Select the DOC plugin
8. Select "V1.0" 
9. Click "Add Document"
10. Click "Update to AAS"
11. Bug: it creates a SMC named `Document{0:00}`, which should be `Document00` instead
12. Select "V1.1" 
13. Click "Add Document"
14. Add a language to "Languages"
15. Add a file to "DigitalFile"
16. Click "Update to AAS"
17. Bug: it creates a property `Language{0}` which should be `Language00` instead.
18. Bug: it creates a file `DigitalFile{0:00}` which should be `DigitalFile00` instead.

**Expected behavior**
The plugin creates correct names (see above)

**Screenshots**
![Document{0:00}](https://github.com/eclipse-aaspe/aaspe/assets/14279507/c63f456a-04c0-4490-bbbc-3d1842e3bcee)

![DigitalFile{0:00}](https://github.com/eclipse-aaspe/aaspe/assets/14279507/c861f14e-1559-4ff7-80f0-0d4648b6549d)

**Desktop (please complete the following information):**
Windows 10 22H2

**Smartphone (please complete the following information):**
N/A

**Additional context**
Version 2024-02-27

**Comment by MichaelHoffmeisterFesto** [comment]
Thank you for the very detailed description of the case!

Current branch name: MIHO/Post_XMAS2023_Bugfixes

* [delete] Contact info plugin had false "create SM" offer
* [added] Docu plugin offer to "Documentation (V1.2)"
* "{0:00}" came from an dead innovation in Form Utils,
  changed back to "{00}" (thus, not version dependent)
* Note: I am a little concerned about the "{00}" notation (although specified and documented), as this could stand in conflict with strict frameworks not allowing "{}" in idShort. 
* Idea: allow also "__00__" ??
* Update: I've changed the code, so that "__00__" can be used in the respective .add.json-files for PresetIdShort; however, I did not implement these changes yet
* [changed] There was still in problem in translating the "{00}", so I changed the behaviour in FormInstance.cs:1203
* Now the test case is performing as intended
* Note: this forms functionality is really demanding (lots of recursions etc.), therefore it is hard to provide best quality of outcome
* What is open is the question to (overall) change notation IdShort "{00}" to "__00__"

**Comment by MichaelHoffmeisterFesto** [comment]
Checked again, seems to work.
All over in AASPE, as well as in "How to write a SMT specification", the change to 
```
__00__
```
is being explained.
